function escapeHtml(str = '') {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderCard(offer) {
  const img = offer.image
    ? `<div class="auto-offers__img" style="background-image:url('${escapeHtml(
        offer.image
      )}')"></div>`
    : '';

  return `
    <div class="auto-offers__card">
      ${img}
      <div class="auto-offers__body">
        <span class="auto-offers__brand">${escapeHtml(offer.brand)}</span>
        <h3 class="auto-offers__title">${escapeHtml(offer.title)}</h3>
        ${
          offer.description
            ? `<p class="auto-offers__desc">${escapeHtml(offer.description)}</p>`
            : ''
        }
        <a class="auto-offers__link" href="${escapeHtml(offer.url)}" target="_blank" rel="noopener noreferrer">
          View Offer
        </a>
      </div>
    </div>`;
}

/**
 * Builds the full HTML block for the Shopify "offers" page body.
 * @param {{yamaha: object[], suzuki: object[]}} offersByBrand
 */
function buildOffersHtml({ yamaha = [], suzuki = [] }) {
  const allOffers = [...yamaha, ...suzuki];
  const updatedAt = new Date().toISOString();

  const cardsHtml = allOffers.length
    ? allOffers.map(renderCard).join('\n')
    : `<p>No current offers found. Check back soon, or visit the Yamaha and Suzuki websites directly.</p>`;

  return `
<!-- Auto-generated by offers-sync. Last updated: ${updatedAt} -->
<style>
  .auto-offers__grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
    gap: 24px;
    margin: 24px 0;
  }
  .auto-offers__card {
    border: 1px solid #e2e2e2;
    border-radius: 8px;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    background: #fff;
  }
  .auto-offers__img {
    height: 160px;
    background-size: cover;
    background-position: center;
    background-color: #f2f2f2;
  }
  .auto-offers__body {
    padding: 16px;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .auto-offers__brand {
    font-size: 12px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #888;
  }
  .auto-offers__title {
    margin: 0;
    font-size: 18px;
  }
  .auto-offers__desc {
    margin: 0;
    font-size: 14px;
    color: #444;
    line-height: 1.4;
  }
  .auto-offers__link {
    margin-top: auto;
    display: inline-block;
    padding: 10px 16px;
    background: #111;
    color: #fff !important;
    text-decoration: none;
    border-radius: 4px;
    text-align: center;
    font-size: 14px;
    font-weight: 600;
  }
  .auto-offers__updated {
    font-size: 12px;
    color: #999;
    margin-bottom: 8px;
  }
</style>
<div class="auto-offers__updated">Offers last synced: ${new Date().toLocaleString('en-NZ', {
    timeZone: 'Pacific/Auckland',
  })} (NZ time)</div>
<div class="auto-offers__grid">
${cardsHtml}
</div>`;
}

module.exports = { buildOffersHtml };
